### ISSUE TITLE
Add more helpers

### ISSUE THREAD

**Issue by siiptuo** [slimphp/Twig-View#1]
Currently this has only `url_for` function. The old Slim-Views has 4 different helpers. A simple solution would be to add `Slim\App` as a global. It would look like this:

    {% if slim.request.isGet %}
        <a href="{{ slim.request.uri.basepath ~ slim.router.urlFor('home') }}">link</a>
    {% endif %}

It's not as pretty as few selected helpers but the API is would same as in PHP code. Unfortunately it would also make it possible to include application logic into templates which may have unwanted side effects.

**Comment by akrabat** [comment]
I'd rather see a PR for specific additional helpers.

**Comment by silentworks** [comment]
These should probably be split back out as the original was, so we have a separate class for the helpers in the repo.

**Comment by akrabat** [comment]
See #22
