### ISSUE TITLE
There is no methods like addFilter, addFunction and etc.

### ISSUE THREAD

**Issue by Awilum** [slimphp/Twig-View#116]
There is no methods like addFilter, addFunction and etc.

```
$function = new \Twig\TwigFunction('function_name', function () {
        // ...
    });

$view->addFunction($function);
```

> [24-Jun-2019 10:11:11 Kwajalein] PHP Fatal error:  Uncaught Error: Call to undefined method Slim\Views\Twig::addFunction() In ....

https://twig.symfony.com/doc/2.x/advanced.html

Should I use 

`$view->getEnvironment()->addFunction($function);`

?

**Comment by adriansuter** [comment]
Hi @Awilum 

You can do it that way. Or you write your custom extension (which I recommend) and add that to twig using the implemented method `addExtension`. See also https://twig.symfony.com/doc/2.x/advanced.html#creating-an-extension

**Comment by l0gicgate** [comment]
I'm closing this as resolved.
