### ISSUE TITLE
[3.x] Decouple the extension definitions from their runtime implementations?

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Twig-View#117]
Hi

In the documentation of Twig, they write that it should be best practice to decouple the extension definitions from their runtime implementations. See https://twig.symfony.com/doc/2.x/advanced.html#definition-vs-runtime

Should we follow that recommendation?

I already tried to implement that. See https://github.com/adriansuter/Twig-View/tree/patch-runtimeExtension

It actually works, but of course, phpunit is giving me 21 errors 😨.

**Comment by adriansuter** [comment]
Should we?

If yes, I guess that this would introduce BC. Too risky?

**Comment by l0gicgate** [comment]
Well since the 3.0.0 branch is still in alpha stage I think we can break stuff. If it makes everything more robust then sure!

**Comment by adriansuter** [comment]
Fine, so I will tackle those unit test cases.
