### ISSUE TITLE
Simplifying queuing middleware

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Twig-View#118]
This issue is similar to https://github.com/slimphp/Slim/issues/2762.

With the solution proposed in https://github.com/slimphp/Slim/issues/2762#issuecomment-514383937, a user could for example just write
```php
$app = AppFactory::create();
$app->addRoutingMiddleware();
$app->addErrorMiddleware(true, true, false)
    ->getDefaultErrorHandler()->forceContentType('application/json');
```
and only `AppFactory` needs to be imported. That is pretty nice for these two internal slim middlewares.

I wonder if we could simplify the other middlewares as well. I mean, for example, to add the twig middleware, a user has to write the following code.
```php
$container = new Container();
AppFactory::setContainer($container);

$app = AppFactory::create();
// Let's add the routing middleware. Nice.
$app->addRoutingMiddleware();

// Let's add the twig middleware. Complicated.
$app->add(new TwigMiddleware(
    new Twig(__DIR__ . '/../templates', [
        'cache' => __DIR__ . '/../cache/twig',
        'auto_reload' => true,
    ]),
    $app->getContainer(),
    $app->getRouteCollector()->getRouteParser(),
    '',
    Twig::class
));

// Let's add the error middleware. Nice.
$app->addErrorMiddleware(true, true, false);
```
We could for example let the user add twig to the container and then he/she can simply call
```php
$app->add(TwigMiddleware::create($app, $basePath, $twigContainerKey));
```
The static `create()` method would then get the container from the app, twig from the container, and the route parser from the app (via route collector). Of course, the method would throw exceptions whenever anything is missing (no container, twig not found, etc.).

**Comment by l0gicgate** [comment]
Yes, let's do that as well. This will simplify everything for the end user tremendously.

**Comment by adriansuter** [comment]
Handled in #120
