### ISSUE TITLE
3.x - Non-Container & Container Usage

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Twig-View#124]
The `TwigMiddleware` should have two operation modes:
* Without PSR-11 Container
* With PSR-11 Container

## Without PSR-11 Container
In case there is no container available, `Twig` would be added as attribute to the `$request` (during the `process()` method). Then the route callback can get `Twig` using the same technique as the `RouteContext::fromRequest()` - for example `TwigContext::fromRequest()`.

## With PSR-11 Container
If there is a container available, `Twig` has to be added to the container by the user (because of pre-compilation, etc.). Then the route callback can get `Twig` out from the container. In this case there is no need to add it as attribute to the request.

## Conclusion
In both cases, the `process()` method of the middleware has to add the extension and the runtime loader.

Concerning the first case, I am not sure if it is a good idea to use the request instance as "some kind of container".

What are your opinions?

**Comment by l0gicgate** [comment]
I agree, we need to enable the possibility to instantiate the `TwigMiddleware` with an instance of `Twig` in case the no container exists.

I also agree that we can carry the `twig` attribute via the request attributes if a container is not present as a fallback

**Comment by bangzek** [comment]
One good way to do that is to make the the container and request attribute orthogonal issue.

Currently we have ::create() that need container but the object itself doesn't need or aware of the container.

I think we're set on container mode, probably just need request attribute on the no container mode.

Let's try to see it from the user side, what kind support they need if they choose to forego container?

**Comment by bangzek** [comment]
Should we add another static helper that's like ::create() but also pass Twig object along with App?
