### ISSUE TITLE
3.x - Twig Constructor Dependency Injection

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Twig-View#125]
Currently, the `\Slim\Views\Twig` constructor instantiates a `\Twig\Loader\FilesystemLoader` (in the `createLoader`-method) and a `\Twig\Environment`.

https://github.com/slimphp/Twig-View/blob/89827f4919f5e803abb5e2f40205f8429ea63108/src/Twig.php#L62-L66

Should we add the possibility to pass them to the constructor, such that a user could create those two instances before and outside of the Twig constructor?

Or do we want to prevent users to bring their own instances? So whenever they need something like this, then they have to extend `Twig` and develop their own implementations.

**Comment by l0gicgate** [comment]
I see this as a convenience thing. But it would make more sense to do dependency injection.

**Comment by bangzek** [comment]
Let's brainstorm a bit.

Can you find a good reason why user need to do that?
What case that scenario is needed?

I'm new on this Slim and Twig thing, so I can't see where it might seem a good idea to do that.

**Comment by adriansuter** [comment]
Maybe we could add either a `TwigFactory` class that contains a static helper method to create `Twig` instances or put a static creator helper into `Twig` itself.

The helper method takes `$path` and `$settings` and would then instantiate the filesystem loader and the environment. The `Twig` constructor on the other hand takes these two instances. So if needed, a user could simply pass them to Twig. For example if the environment comes from a pre-compiled container.

**Comment by bangzek** [comment]
I prefer static factory helper rather than another class just to run factory.

Now I see the value in injecting dependency for Twig, a good case is if instead filesystem loader you want a database backed loader for example.
