### ISSUE TITLE
3.x - Travis-CI

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Twig-View#128]
Is there a reason why the 3.x branch does not have a working Travis-CI?

**Comment by l0gicgate** [comment]
Nope, we should have CI on all the repos. It really just hasn't been taken care of

**Comment by l0gicgate** [comment]
I just realized, there's no builds on anything but the main branch which is currently master. I'm going to copy master into the 2.x branch once we switch the main branch of the repo to be 3.x. Until then, there won't be any Travis/Coveralls
