### ISSUE TITLE
base_path twig function missing

### ISSUE THREAD

**Issue by FvsJ101** [slimphp/Twig-View#155]
I have the latest slim/twig-views for my project

"require": {
        "slim/slim": "4.0.0",
        "vlucas/phpdotenv": "^2.5",
        "phpmailer/phpmailer": "^6.0",
        "illuminate/database": "^5.4.36",
        "slim/psr7": "^0.5.0",
        "slim/flash": "^0.4.0",
        "slim/csrf": "^1.0",
        "bryanjhv/slim-session": "^4.0",
        "league/container": "^3.3",
        "slim/twig-view": "3.0.0-beta"
    },

However I noticed in the  TwigExtension class base_path function is missing?

**Comment by odan** [comment]
The `base_path` function has not been released in version 3.0.0-beta and should be available in the next version.

**Comment by FvsJ101** [comment]
Any idea when that will be?
