### ISSUE TITLE
Slim\Views\Twig::create does not exist

### ISSUE THREAD

**Issue by Maadtin** [slimphp/Twig-View#157]
I've installed the 3.x beta and the Twig class inside Slim\Views does not have a method `create` like in the example on the readme, can anyone help me please? trying to use it with slim 4

**Comment by GameplayJDK** [comment]
I had this issue too yesterday.

The problem is, that the `3.0.0-beta` version, which is advised to install in the readme, is not the version that contains the `::create()` method yet.

You will have to install the `3.0.0-dev` version to access that method.

**Comment by Maadtin** [comment]
@GameplayJDK  Hello, thanks for the reply, But how could I Install this dev version?
`composer require slim/twig-view:3.0.0-dev` throws an errors telling me that the version does not exist.

**Comment by GameplayJDK** [comment]
I changed it in `composer.json` manually. Should work the same in console. Have you tried deleting the `composer.lock` file (and `vendor` folder)?

This is the line from my `composer.json` file:
```json
{
    ...
    "slim/twig-view": "^3.0.0-dev"
    ...
}
```
I don't know, if the roof char is important for installing dev versions, though.
