### ISSUE TITLE
Coupling this with flash messages? (An array)

### ISSUE THREAD

**Issue by Codexing** [slimphp/Twig-View#16]
What is the best way of coupling this with flash messages? 

Currently, I want to do this:

    $app->get('/flash', function ($request, $response, $args) use ($app) {
        $this->flash->addMessage('flash', 'This is a message');
        return $response->withStatus(302)->withHeader('Location', '/');
    });
    
    $app->get('/', function ($request, $response, $args) use ($app) {
        $flashes= $this->flash->getMessages();  
        return $this->view->render($response, 'home.php', [
            'messages' => $flashes
        ]);
    })->setName('home');

And then:
`    {% for flash in messages %}`
`    {{ flash }}`
`    {% endfor %}`

However, I am getting an error:
Notice: Array to string conversion in ... /vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code on line 29

Not sure if I am making a complete amateur mistake here in how I am sending the array over. Or is this simply not possible?

**Comment by yeekit24** [comment]
Hi can i know is this issue solved? i hit the similar issue with php 5.5 and slim 3
