### ISSUE TITLE
Rendering no space

### ISSUE THREAD

**Issue by julzlegaspi** [slimphp/Twig-View#163]
Hello, 
I am using twig-view in my slim application, the version that I am using is `slim/twig-view": "^2.3`. In my application, I have these variables declared `{{first_name}} {{last_name}} ` and it supposed to render like `John Doe` after I upgraded my PHP version from `7.0` to `7.4` the output becomes `JohnDoe`. space between first name and last name cannot recognize. Can anyone have the same issue?thank you

**Comment by nixoncode** [comment]
Hi @julzpalomiano have tested on slim `^2.3`  and the latest version `3.0` but your issue cannot be replicated.

ensure in your html you are adding a space e.g
`<p>{{ first_name }} {{ last_name }}</p>`

This should work just fine. Read more on space control [here](https://symfony.com/blog/better-white-space-control-in-twig-templates).

tip: consider upgrading to the latest version
