### ISSUE TITLE
Fix incorrect declaration

### ISSUE THREAD

**Issue by ccwebdesign** [slimphp/Twig-View#164]
Using:
PHP: 7.4
Slim: 4.4

Error message: Fatal error: Declaration of Slim\Views\TwigRuntimeLoader::load($class) must be compatible with Twig\RuntimeLoader\RuntimeLoaderInterface::load(string $class)...

Fork (fixed) at:
https://github.com/ccwebdesign/Twig-View

The issue is that Twig 2.x (requiring PHP 7.x) has this declaration: load($class), while Twig 3.x (requiring PHP 7.2.5+) has load(string $class).

If PHP <7.2.5 / Twig 2.x needs to be supported, removing strict_types from TwigRuntimeLoader is the simplest method.

**Comment by ccwebdesign** [comment]
Derp, ignore this -- completely my issue with mismatched PHP versions between server and composer install.

**Comment by mridah** [comment]
Hi @ccwebdesign @akrabat @adriansuter 

I'm facing the same issue on my server. It runs fine on my local pc. How can I resolve this?

Server specs:
Ubuntu 18.04
Slim4
PHP PHP 7.2.29 ( my local system has 7.2.24 )

this is my composer.json

        "slim/slim": "4.0.0",                <--
        "vlucas/phpdotenv": "^4.1",
        "slim/twig-view": "3.0.0",        <--
        "slim/psr7": "^1.0",
        "php-di/php-di": "^6.1",
        "dompdf/dompdf": "^0.8.5",
        "faapz/pdo": "^2.0",
        "phpmailer/phpmailer": "^6.1"

Even commenting out `declare(strict_types=1);` in `slim/twig-view/src/TwigRuntimeLoader.php` doesn't help

**Comment by ccwebdesign** [comment]
For me, the issue was that the PHP version in my path was different from the PHP version on the actual server. From that, composer installed a different version of Twig, which then broke everything. Make sure those match.

Or you could also add a PHP platform version to composer.json (I think) with:
```
"config": {
    "platform": {
        "php": "7.2.29"
    }
}
```
