### ISSUE TITLE
Composer Slim 3

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Twig-View#18]
Hello, I can use composer to get Twig-View, but not to get Slim in version 3. But Twig-View would only work with version 3. Is it possible to add Slim in version3 to the packagist for composer?
By the way, thanks for this amazing framework.

**Comment by silentworks** [comment]
Hi @adriansuter, you can do `composer require slim/slim:"3.0.x@dev"` to get v3 from packagist.

**Comment by adriansuter** [comment]
Okay. Thanks it worked.
