### ISSUE TITLE
Using view outside a request/response cycle does not load the Slim/Views/TwigExtension

### ISSUE THREAD

**Issue by Mark-H** [slimphp/Twig-View#189]
I've just been hitting my desk for half an hour trying to figure out why the `url_for` function wasn't available in an email template that gets sent by a cron process, but it's because the TwigExtension provided by this package is added as a middleware.

For example I'm creating the app like this inside a PHP-DI definition:

```
    AppFactory::setContainer($c);
    $app = AppFactory::create();

    // ... other irrelevant things ...

    // Next, routing middleware. Needs to be added before the view
    $app->addRoutingMiddleware();

    // Twig middleware adds twig loader and extensions
    $app->add(TwigMiddleware::createFromContainer($app));
```

Works fine in the front-end, but a cron process that tries to use `$container->get('view')->fetch('template.twig')` fails to load the TwigExtension and therefore doesn't have the url_for function available to it. :(

I've managed to workaround it by adding the following to the cron command (based on the TwigMiddleware class):

```
use Slim\Routing\RouteCollector;
use Slim\Routing\RouteParser;
use Slim\Views\TwigExtension;
use Slim\Views\TwigRuntimeLoader;

$view = $container->get('view');

$runtimeLoader = new TwigRuntimeLoader($container->get(RouteParser::class), new Uri('root url of site'), $container->get(RouteCollector::class)->getBasePath());
$view->addRuntimeLoader($runtimeLoader);

$extension = new TwigExtension();
$view->addExtension($extension);
```

I wonder if I've done something wrong / if there's a different way to register this extension without duplicating the init code / this should be a documented edge case.

**Comment by l0gicgate** [comment]
That’s not an edge case. This is your particular use case which isn’t really the way this library is intended to be used. 

It’s meant to be used with a Slim app, not as a standalone renderer for cron jobs or other.

**Comment by Mark-H** [comment]
Appreciate the quick response. 

I respectfully disagree though - this is in fact a Slim application; it just has a (small) part of that application which happens outside the request/response cycle, and it caught me off-guard that the provided functions to generate URLs appropriately were suddenly not available.

**Comment by neubreed** [comment]
How do we send emails from a cron / command console that render a template with url_for or other Slim/Views/TwigExtension functions?
