### ISSUE TITLE
Support for flash

### ISSUE THREAD

**Issue by neilmillard** [slimphp/Twig-View#21]
Not sure if this is covered in the missing helpers, should this support flash messages?

**Comment by Melbournite** [comment]
It does, but you need to send it over to the template.

For example:
    $app->flash->addMessage('flash', 'This is a message');
    return $response->withStatus(302)->withHeader('Location', $app->router->pathFor('home'));

Then in 'Home':
    $messages = $this->flash->getMessage('flash');

Include it by rendering out 'messages' to twig):
    return $this->view->render($response, 'template.twig', [
        'flash' => $messages,
    ]);    

Then in template.twig:
    {% if flash %}
    {% for flash in flash %} <- if multiple.

**Comment by neilmillard** [comment]
Ah, okay, I can write some middleware to inject the messages into the template regardless of the route.
Thanks

```php
$messages = $this->flash->getMessage('flash');
$this->view->offsetSet('flash',$messages);
```
