### ISSUE TITLE
How to generate URL for path?

### ISSUE THREAD

**Issue by piotr-cz** [slimphp/Twig-View#24]
The `path_for` returned string starts with a slash, this is inconvenient for applications inside a subdirectory.

Example:

*Route definition*
```php
$app->get('/{slug}', 'App\Action\ItemAction:dispatch');
```
*Template*
```twig
<a href="{{ path_for('item', {'slug': item.slug}) }}">
  {{ item.name }}
</a>
```
produces `/itemslug`, which is evaluated inside a browser to `http://localhost:8000/itemslug` on my dev server. As my application is within `project/alpha` subdirectory, I'd prefer some helper function which creates as string which evaluates to `http://localhost:8000/project/alpha/itemslug`.

In the head of the document I'm using base element `<base href="{{ base_url() }}/" />` so all links may be relative.

I can use both: `base_url() ~ path_for()` but IMHO it's an overhead to list scheme, domain, port etc in each hyperlink - a relative or absolute path would be sufficient.

So I wonder how the application URLs should be created in the Twig-View?

Reintroduce the `url_for` function which would create URLs not paths, or trim starting slash in `path_for`? If so, should it happen it in the Twig-View or in the Slim::Router package?

**Comment by piotr-cz** [comment]
Thinking again about it, bulletproof solution would be a function generating an absolute path. 
This is how links are generated in Joomla CMS.

**Comment by nicokaag** [comment]
My suggestion would be:

Having a `path_for` function which which returns the "absolute" path, and takes an optional parameter like `relativePath`, that returns the path as exactly defined in the routing.
The reason for returning the absolute path by default is that it's by far the most used use-case. In your case it's that your project runs in a sub-directory, but also when using index.php, and you have no pretty url rewriting, it will always break.

And another function `url_for`, pretty much doing the same as `path_for`, but with the url in front of it.

**Comment by piotr-cz** [comment]
Reading the https://github.com/slimphp/Slim/issues/1326, I see that the **Uri::getBaseUrl()** method have been created to solve this problem in Slim.

I'd just need something slightly similar for views.

**Comment by silentworks** [comment]
@piotr-cz that is also available in the view now.

```
{{ base_url() }}
```

So you could do:

```
{{ base_url() }}{{ url_for('my_route_name') }}
```

**Comment by piotr-cz** [comment]
@silentworks
I know, but why having two functions, each of very little use on it's own in views instead of one?

I'd use `base_url` in `<base href />` tag. In links to assets I'd rather use absolute path on server, without a scheme and hostname. But it's a matter of preference.

I can't think of scenario when I'd use `path_for` in current state at all.

**Comment by silentworks** [comment]
I think this is an improvement, before we only had `url_for` which is now `path_for`, but now we also have `base_url` for those who want to make use of it.

**Comment by akrabat** [comment]
I use `path_for` by itself in my project with no problems.

**Comment by nicokaag** [comment]
For me it kind of feels wrong that `path_for` breaks with a basic project setup, where you don't use url-rewriting. The example in the readme will only work if you use url-rewriting to get rid of the `index.php`.

But I think that that is more an issue for the Slim project itself, and not this one(?).

**Comment by piotr-cz** [comment]
@akrabat Did you try putting a project in a subfolder?

My structure is:

```
http://localhost:8000
  /clients
    /foo
    /bar
  /personal
    /helloWorld
```

When I use path_for in the `/personal/hellloWolrd` project, it generates strings like `/contact` so 
URL is resolved to `http://localhost:8000/helloWorld/contact`, which makes apache to return 404 error.

**Comment by silentworks** [comment]
@piotr-cz Is this not solved by adding `base_url` before `path_for`?

**Comment by piotr-cz** [comment]
@silentworks It is, but what's the use case for `path_for` at all?

**Comment by akrabat** [comment]
I don't run my projects like that. I was responding to your assertion "I can't think of scenario when I'd use path_for by itself in current state at all." to point out that it is useful for my use-case and works exactly as I expect.

There's a reasonable argument for  `{{ base_path_for('routename', {foo: "bar:}) }}`, which if someone wants to PR, I'm sure @silentworks or myself would review and merge.

I don't want `path_for` to change as it's a direct mapping to the router's `pathFor` and it would be very confusing to have `pathFor` and `path_for` do different things.

**Comment by silentworks** [comment]
@piotr-cz the same use case `url_for` had before, most of my project's are not installed in subdirectories and `path_for` is sufficient for me. I don't actually want full url at all times as I only want the path.

**Comment by piotr-cz** [comment]
I'll prepare a pull request for `base_path_for` then, this makes sense.

Probably this will solve the issue @nicokaag is having.

Placing projects in subfolders is the way I run multiple projects on one vagrant box, but it may also be helpful for plugging api created in Slim into a `/api` folder in existing project.

**Comment by akrabat** [comment]
Thanks. I appreciate that its a valid use-case, along with the index.php one.

**Comment by piotr-cz** [comment]
@nicokaag Can you please check if #27 solves your issue?

**Comment by nicokaag** [comment]
@piotr-cz it does work. 

I do still wonder if the Slim\Router pathFor method shouldn't solve this.
In Slim 2, the urlFor method already solves this.

Is there a separate issue list for Slim 3 where these kind of things can be discussed?

**Comment by silentworks** [comment]
@nicokaag I cannot see how urlFor in Slim 2 solved this, pathFor is the same as urlFor, just the name change.

**Comment by nicokaag** [comment]
Ah, I see now that Slim 2 has an extra method in the `Slim\Slim` class, also called urlFor, that solves the issue, so that you can do `$app->urlFor('name', $params);`. And that function looks like:

```
public function urlFor($name, $params = array())
{
    return $this->request->getRootUri() . $this->router->urlFor($name, $params);
}
```

Not sure if that is actually something that you'd want.

**Comment by piotr-cz** [comment]
This could be helpful in the Slim too, for example for creating redirects.

But it should not be called pathFor, because it implies using paths. Maybe it should be rather called `urlFor` (full url) or `basePathFor` (absolute path)  what do you think?

**Comment by akrabat** [comment]
The Router's `pathFor` is now base path aware and returns an absolute URL relative to the domain name.

See https://github.com/slimphp/Slim/pull/1443

**Comment by piotr-cz** [comment]
great.
