### ISSUE TITLE
3.3.0 Release date

### ISSUE THREAD

**Issue by adoy** [slimphp/Twig-View#240]
Hi

I'm moving our company's codebase to PHP8.1 and having deprecation warnings because of Twig-View. After having a quick look I found out that the `3.x` branch is PHP8.1 ready. I would like to avoid having to use `dev-3.x` in my dependencies. Do you have any plan to release 3.3.0 soon ?

Thanks a lot for your work !

**Comment by icetee** [comment]
Yes, a new release would be great. Until then, unfortunately, it will remain:
```json
    "slim/twig-view": "3.x-dev",
```

**Comment by l0gicgate** [comment]
Here you go:
https://github.com/slimphp/Twig-View/releases/tag/3.3.0

**Comment by adoy** [comment]
@l0gicgate Thanks a lot :-)
