### ISSUE TITLE
Usage example in Readme.md not working.

### ISSUE THREAD

**Issue by nicokaag** [slimphp/Twig-View#26]
When I tried implementing this, using the usage example, it didn't work.

The first thing it "crashed" on, was that there is no "addExtension" method for the class \Slim\Views\Twig.
After checking it out, it looks like there should be a getEnvironment call before that. So it will be:
```
$view->getEnvironment()->addExtension(new Slim\Views\TwigExtension(
```

Which brings us to the next issue, there is no Slim\Views\TwigExtension class.

Any ideas?

**Comment by silentworks** [comment]
These all exist on the master branch at the moment, I think I need to tag it so you can get it via composer without having to do `dev-master`.

**Comment by silentworks** [comment]
I have just tagged master so you should get the latest changes on `composer update` if you have your version constraint set correctly.

**Comment by nicokaag** [comment]
It works now, for anyone interested, the version constraint I'm using now is: `^1.1`

**Comment by nicokaag** [comment]
I may have been a bit to quick closing this issue.

In the readme, you use `{{ url_for('profile', { 'name': 'josh' }) }}`
This now seems to be changed to path_for in the new version. (As url_for worked before this update)

**Comment by silentworks** [comment]
Good catch, fixed.
