### ISSUE TITLE
`composer require slim/twig-view:^3.0` handle PHP Version Problem

### ISSUE THREAD

**Issue by cesu171** [slimphp/Twig-View#261]
When I try to run `composer require slim/twig-view:^3.0`

I got this error message
`Your requirements could not be resolved to an installable set of packages.`

`  Problem 1`
`    - Root composer.json requires slim/twig-view 3.0 -> satisfiable by slim/twig-view[3.0.0].`
`    - slim/twig-view 3.0.0 requires php ^7.1 -> your php version (8.1.4) does not satisfy that requirement.    `

`Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Comment by nbayramberdiyev** [comment]
You're trying to install the version 3.0.0 which is not supported on PHP 8.1. Please, install the latest release:

```shell
composer require slim/twig-view
```
