### ISSUE TITLE
Where is \Slim\App?

### ISSUE THREAD

**Issue by iflickle** [slimphp/Twig-View#29]
The instructions for this repo dont seem to work for me
I installed the Slim Framework from the home and documentation which works fine first time.
Yet when i install Twig View i get many application inconsistancies such as file class names not available.

and Searching your repo is seems Slim\App doesnt even exist?

**Comment by silentworks** [comment]
This is for Slim 3 only, based on the issues you are having I would say you are using Slim 2, you need the [Slim Views](https://github.com/slimphp/Slim-Views) repo for that.

**Comment by iflickle** [comment]
ok thanks for pointing this out. i think you should add the version number to the repo title or readme page, as i do find with a lot of repos people dont specify software versions and dependecies

**Comment by iflickle** [comment]
it would be good to add a bash script which does the checks install.sh

**Comment by iflickle** [comment]
in theory that what composer if for but not many people use the installer section in composer

**Comment by iflickle** [comment]
i just read it on there lol
