### ISSUE TITLE
Twig_EnvironmentInterface does not exist

### ISSUE THREAD

**Issue by Swader** [slimphp/Twig-View#31]
[This interface](https://github.com/slimphp/Twig-View/blob/master/src/Twig.php#L135) does not exist in Twig.

Where is it defined? The Twig project only has [Environment](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php) and that one has no interface.

**Comment by akrabat** [comment]
No idea :) Feel free to PR a fix!

**Comment by Swader** [comment]
Ok, submitted #32
