### ISSUE TITLE
How to set global value

### ISSUE THREAD

**Issue by rhnkyr** [slimphp/Twig-View#38]
Hi there. In Slim 2 i can set key in __construct like $this->view->set("foo","bar") via Slims/View. But in Slim 3 with Twig-view i can not set twig value in it. How can i set val outside of render function?

**Comment by silentworks** [comment]
This should do the trick

```php
$app = new Slim\App();

$twig = $app->view-> getEnvironment();
$twig->addGlobal('foo', 'bar');
```

or you should be able to also do:

```php
$app = new Slim\App();
$app->view['foo'] = 'bar';
```
