### ISSUE TITLE
Add additional data to View

### ISSUE THREAD

**Issue by dewey92** [slimphp/Twig-View#40]
In Slim 2, I can easily add data before rendering with $this->view->appendData([]); However, In Slim 3, the only possible for me to do so is with $this->view->offsetSet($key, $value);

I think it would be great to pass an array instead of key value pair

**Comment by mathmarques** [comment]
You don't need to use:
```php
$this->view->offsetSet($key, $value);
```

You can use:
```php
$this->view['key'] = 'value';
```
Or on render:
```php
$this->view->render($response, 'profile.html', [
    'key' => 'value',
    'anotherKey' => 'value'
]);
```
The data array passed via render will be merged with the data inserted before

**Comment by dewey92** [comment]
@mathmarques Cool! I don't even know it uses magic setter. Thanks!

**Comment by mathmarques** [comment]
np :)

Implements \ArrayAccess in fact

**Comment by dewey92** [comment]
Oh my bad, yeah I can't find any setter method lol

**Comment by matthew-dean** [comment]
This is great buuuuut.... appendData works for every request. What if you don't want to do that for each call to `render()` ?
