### ISSUE TITLE
Accessing flash messages from twig

### ISSUE THREAD

**Issue by glazilla** [slimphp/Twig-View#47]
Hi,

With slim previous version (2.x), it was quite easy to access flash messages from twig... This feature was quite useful. Any idea on when something similar will be available ?

Regards,

Sylvain

**Comment by geggleto** [comment]
@glazilla 

You can add anything to twig via...

```php
$view->getEnvrionment()->addGlobal('flash', []);
```

**Comment by glazilla** [comment]
Yes, of course. This is what I use to add some global info to all my twig views. But, by doing this way, I think the flash message will be persistent and won't disappear on next view...

**Comment by erdemece** [comment]
I need an answer to this as well.

**Comment by geggleto** [comment]
Flash messages disappear on the next view. it has nothing to do with TWIG.
