### ISSUE TITLE
render doesn't use $this->defaultVariables

### ISSUE THREAD

**Issue by sirber** [slimphp/Twig-View#49]
From the code:

public function fetch($template, $data = [])
{
    $data = array_merge($this->defaultVariables, $data);

    return $this->environment->loadTemplate($template)->render($data);
}

public function render(ResponseInterface $response, $template, $data = [])
{
     $response->getBody()->write($this->fetch($template, $data));

     return $response;
}
in "fetch" I can use pre-added variables but not in render.

**Comment by mathmarques** [comment]
If you read the render function carefully you will see that render uses the fetch function.
So, nothing wrong here.

**Comment by sirber** [comment]
you're right, my bad :)
thank you!
