### ISSUE TITLE
Multiple paths per namespace

### ISSUE THREAD

**Issue by ugsite** [slimphp/Twig-View#52]
How to use multiple paths per namespace?

**Comment by NigelGreenway** [comment]
@ugsite You would need to pass the root directory of where your directories are stored.

See [here](https://github.com/slimphp/Twig-View/blob/master/tests/TwigTest.php#L49) for an example.

__quick explanation:__

If you have `dir_1`, `dir_2` and `dir_3` that are within the `templates` directory, you would do the following:

```php

$templateDirectories = [
   'MyTemplates' =  'some/path/to/templates`,
];

$twig = new Slim\Views\Twig($templateDirectories);
```

In you `render` method, you would pass `@MyTemplates/some/where/your.html.twig`. If you had multiple template directories, you would do

```php

$templateDirectories = [
   'MyTemplatesA' =  'some/path/to/templates',
   'MyTemplatesB' =  'another/path/to/templates',
];

$twig = new Slim\Views\Twig($templateDirectories);
```

You would then call the first templates with `@MyTemplatesA/some/directory/file_a.html.twig` and `@MyTemplatesB/other/file_b.html.twig`.

Hope this helps

**Comment by ugsite** [comment]
@NigelGreenway thank you for answer.

In this example you use one path per namespace, but how to use multiple paths per namespace, path_1, path_2, path_3 in namespace_1. How to use path_1, path_2, path_3 in main namespace?

**Comment by silentworks** [comment]
@NigelGreenway can you change the `$loader->addPaths()` call to `$loader->setPaths()` and this would give the previous setup. I didn't realise we just broke BC with this change, but it should be noted on line 53 that `$path` was only defined to take a string although an array worked. So I am not too sure if this is a BC break. If we use `setPaths()` the developer can do:

```php
$templateDirectories = [
   'MyTemplatesA' =  [
       'some/path/to/templates', 
       'more/path/to/templates'
   ],
   'MyTemplatesB' =  'another/path/to/templates',
];

$twig = new Slim\Views\Twig($templateDirectories);

**Comment by NigelGreenway** [comment]
Apologies, I will get on to this at lunch today.

**Comment by silentworks** [comment]
No worries @NigelGreenway, I think it was just badly documented code on our path. There was no way to tell that `Twig_Loader_Filesystem` would take and array unless you looked at that class itself. We didn't seem to add that to the docblock for the constructor of `Slim\View\Twig`.

**Comment by ugsite** [comment]
@silentworks, @NigelGreenway thank you very much!

**Comment by NigelGreenway** [comment]
@silentworks, @ugsite Can you confirm that you are happy with this fix before I submit a PR?

@silentworks I would like to do some cleaning on certain parts, I am right to do this in an entirely separate branch?

**Comment by NigelGreenway** [comment]
ps/ sorry for the delay...

**Comment by ugsite** [comment]
@NigelGreenway, @silentworks 
```php
if (is_string($namespace)) {
    $loader->setPaths($path, $namespace);
} else {
    $loader->addPath($path);
}
```

**Comment by silentworks** [comment]
@ugsite don't understand fully what you are suggesting, are you saying we should use that code in the constructor instead or inside the `addPath` method?

**Comment by NigelGreenway** [comment]
@ugsite: I am also confused with what your comment means?

**Comment by ugsite** [comment]
@silentworks, @NigelGreenway
```php
private function addPaths(array $paths)
{
    $loader = new \Twig_Loader_Filesystem();

    foreach ($paths as $namespace => $path) {
        if (is_string($namespace)) {
            $loader->setPaths($path, $namespace);
        } else {
            $loader->addPath($path);
        }
    }

    return $loader;
}
```

**Comment by NigelGreenway** [comment]
@ugsite what is the difference, so I understand it more 😊

**Comment by ugsite** [comment]
We can use 
```php
$twig = new Slim\Views\Twig(['path_1', 'path_2', 'path_3']);
```
and
```php
$twig = new Slim\Views\Twig(['namespace_1' => ['path_1', 'path_2']]);
```

**Comment by NigelGreenway** [comment]
Awesome. I will do that along with the tests to reflect the code.

Cheers @ugsite

**Comment by ugsite** [comment]
@NigelGreenway thank you!

**Comment by NigelGreenway** [comment]
I am just about to submit a PR, but wondered if you wanted a look.

I have created a test, and believe that there are enough tests to cover the changes.

cc/ @ugsite @silentworks 

Again, sorry for the BC break.

**Comment by akrabat** [comment]
@NigelGreenway please raise the PR :)

**Comment by NigelGreenway** [comment]
@akrabat done :)
