### ISSUE TITLE
how to render twig template in variable

### ISSUE THREAD

**Issue by maqboolkhan** [slimphp/Twig-View#54]
in slim 2 
we have render function
as
` $app->render('email.twig')'

but in slim we have to add $response in twig render :( is there any way to render templates without using $response or hold twig render in a variable?

**Comment by NigelGreenway** [comment]
If I am not mistaken, this is because Slim3 is built with [PSR7](http://www.php-fig.org/psr/psr-7/), so you will always need to pass the `response` back to twig on the `render` method.

**Comment by maqboolkhan** [comment]
oohh means i m in trouble as we need to send an HTML email to our client and our strategy is to use a template which is render by twig then pass to email body :( now how to implement it??

**Comment by NigelGreenway** [comment]
@maqboolkhan How do you send emails? You can still build the content from a template by using the [fetch](https://github.com/slimphp/Twig-View/blob/master/src/Twig.php#L88) method from what I remember?

**Comment by maqboolkhan** [comment]
thank you so mucccch @NigelGreenway it worked :)

**Comment by NigelGreenway** [comment]
no problem

**Comment by NigelGreenway** [comment]
Are you happy for this to be closed?

**Comment by maqboolkhan** [comment]
yes :)
