### ISSUE TITLE
Twig doesn't show anything

### ISSUE THREAD

**Issue by be-ndee** [slimphp/Twig-View#67]
I'm using the twig view helper and it does not show anything... There is no error, nothing, just a blank white page. The server says "200"... I don't know what I'm doing wrong.

For example if I use the php-view package or simply do `$response->getBody()->write("foo")` it works. But with the twig-view it doesn't work.

```
app/
    cache/
    templates/
        home.twig
    src/
        App.php
        Twig.php
        Home.php
        ...
public/index.php
vendor/
...
```

I have my own App class, which holds an object of Slim\App. Here I create an object of my own `Twig` class, which executes this code:

```
$container = $app->getContainer();
$container["view"] = function ($container) {
    $view = new Slim\Views\Twig("../app/templates", [
        "cache" => "../app/cache"
    ]);

    $view->addExtension(new Slim\Views\TwigExtension(
        $container["router"],
        $container["request"]->getUri()
    ));

    return $view;
};
```

And instantiate an object of the `Home` class, with this code:

```
$app->get("/", function ($request, $response, $args) {
    return $this->view->render($response, "home.twig", []);
});
```

My template `home.twig` contains just `<h1>Hello world!</h1>`.

Can someone help me? Or do you need more information?

**Comment by be-ndee** [comment]
I tried twig-view in a test project where all the code lives in the index.php. There it works... But it's basically the same code.

**Comment by silentworks** [comment]
Check your server logs, there is something wrong in your own code, I can't say exactly what it is as I can't see your code.

**Comment by geggleto** [comment]
Yep check the server logs... if you are getting a white screen there is another problem someplace else.

what version of PHP are you using?

**Comment by be-ndee** [comment]
Ok, just have a look at my repo "slim-website". I started the built-in webserver of php with `php -S localhost:8001 -t public/`. My PHP version is 5.5.31.

Hopefully you will find something...

**Comment by budactw** [comment]
You can try to disable cache , maybe error message be show
` $view = new Slim\Views\Twig("../app/templates");`

**Comment by geggleto** [comment]
White screen on death is always related to a server environment problem, mainly the lack of a dependency of some sort.

**Comment by givanov2** [comment]
I bet the error message would be this:
````
Warning: file_get_contents(templates/home.twig): failed to open stream: No such file or directory in C:\xampp\htdocs\twig\vendor\twig\twig\lib\Twig\Loader\Filesystem.php on line 131
```

I'm inclined to say it's a bug in the new Twig version (`v1.26.1`), because it works fine with `v1.24.2`. I've posted a question about it (here)[http://stackoverflow.com/questions/40009452/twig-template-language-error], patiently waiting for the answer.

**Comment by geggleto** [comment]
@givanov2 did you try removing your TWIG cache and retrying?

**Comment by givanov2** [comment]
@geggleto, not using cache. Path to templates is the only variable I pass to `Slim\Views\Twig` constructor.

**Comment by geggleto** [comment]
@givanov2 you should be setting the cache to false

**Comment by givanov2** [comment]
```
$templatesPath = '../templates';
$twig = new Slim\Views\Twig($templatesPath, [
    'cache' => false
]);
```
Same result. Would you like me to upload the code to a repository?

**Comment by geggleto** [comment]
Wouldn't hurt.

**Comment by geggleto** [comment]
So your problem is in your relative links to the templates directory.

### settings.php
```php
return [
    Slim\Views\Twig::class => function (ContainerInterface $c) {
        $templatesPath = __DIR__.'/templates'; //Use absolute links

        $twig = new Slim\Views\Twig($templatesPath, [
            'cache' => false
        ]);

        $twig->addExtension(new Slim\Views\TwigExtension(
            $c->get('router'),
            $c->get('request')->getUri()
        ));
        return $twig;
    }
];
```

**Comment by givanov2** [comment]
Mother of God. Thank you, @geggleto!

Yet with Twig v1.24.2 the relative path works fine.

**Comment by geggleto** [comment]
Oh interesting... ¯\_(ツ)_/¯

**Comment by jkalousek** [comment]
I had exact same problem. Thank You @geggleto for solution!
