### ISSUE TITLE
path_for not working

### ISSUE THREAD

**Issue by Idreesshahzaib** [slimphp/Twig-View#68]
I am getting error
 Unknown "path_for" function in "/Templates/Partials/index.twig" at line 11.
here is index .twig

`{% extends "Base.twig" %}`

`{% block content %}`
    
    <header class="main_menu_sec navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="lft_hd">
                        <div class="logo">
                        <a href="{{ path_for('home') }}">Gowarbaam</a>
                        </div>
                    </div>
                </div>

here is view in container
`$container['View'] = function ($container)
{
    return new \Slim\Views\Twig( __DIR__ . '/../App/Views',[
        'cache'     => false //dirname(__FILE__) . '/../Caching'
    ]);

   ```
 $View->addExtension(new Slim\Views\TwigExtension(
        $container['router'],
        $container['request']->getUri()

    ));
```
   

    return $View;
};`

**Comment by geggleto** [comment]
doesn't look like you are adding the extension properly.

**Comment by 1f7** [comment]
`path_for('home')` work for named routes with **setName**
f.ex.
`$app->get('/', 'App\Controllers\Home:index')->setName('home');`

**Comment by geggleto** [comment]
answered.

**Comment by Cvar1984** [comment]
> `path_for('home')` work with named routes with **setName**
> f.ex.
> `$app->get('/', 'App\Controllers\Home:index')->setName('home');`

Im on slim4 is ->setName method from routing got removed? path_for is also not working for me
this is my route
```
$app->any('/home', \App\Controller\HomeController::class)->setName('home');
```
```
{{ path_for('home') }}
```

**Comment by l0gicgate** [comment]
> Im on slim4 is ->setName method from routing got removed?

@Cvar1984 no, it's still here:
https://github.com/slimphp/Slim/blob/4.x/Slim/Interfaces/RouteInterface.php#L85

> path_for is also not working for me

The functionality has moved to the `RouteContext` object:
http://www.slimframework.com/docs/v4/objects/request.html#obtain-base-path-from-within-route

**Comment by Cvar1984** [comment]
> > Im on slim4 is ->setName method from routing got removed?
> 
> @Cvar1984 no, it's still here:
> https://github.com/slimphp/Slim/blob/4.x/Slim/Interfaces/RouteInterface.php#L85
> 
> > path_for is also not working for me
> 
> The functionality has moved to the `RouteContext` object:
> http://www.slimframework.com/docs/v4/objects/request.html#obtain-base-path-from-within-route

I got `string(0) ""` from
```
$view = \Slim\Views\Twig::fromRequest($request);
$basePath = \Slim\Routing\RouteContext::fromRequest($request)->getBasePath();
```
I want to get absolute url for loading assets, i have try using [twig-assets](https://github.com/odan/twig-assets) too, but it wont't load an images

**Comment by zamronypj** [comment]
`path_for` is removed in commit [71d9bb9cc68](https://github.com/slimphp/Twig-View/commit/71d9bb9cc6825c0e327ddbb331d456c6e6357ebd#diff-b0403a6465a130ebc6da9ee0f6ea055d). Replace with `url_for()` or `full_url_for()`.
