### ISSUE TITLE
isCurrentPath() fails if $uri is a string

### ISSUE THREAD

**Issue by claviska** [slimphp/Twig-View#69]
The `is_current_path` method introduced in #64 is really useful. 👍 

However, the method fails if the class is invoked with a string URI ([see line #60](https://github.com/slimphp/Twig-View/blob/master/src/TwigExtension.php#L60)) as demonstrated in the docs:

```php
// Instantiate and add Slim specific extension
$basePath = rtrim(str_ireplace('index.php', '', $c['request']->getUri()->getBasePath()), '/');
$view->addExtension(new Slim\Views\TwigExtension($c['router'], $basePath));
```

It works fine when invoked using `$c['request']->getUri()`:

```php
$view->addExtension(new \Slim\Views\TwigExtension($c['router'], $c['request']->getUri()));
```

Curious — what's the advantage of using the docs approach over `$c['request']->getUri()`?

**Comment by willpoint** [comment]
I noticed that the ```is_current_path``` method fails in the twig template as it's called with a string . How can it be fixed...

**Comment by Tarpsvo** [comment]
I now use the same solution to make `is_current_path` work. Thank you for this fix, would have taken me ages to figure the cause out on my own.

**Comment by nbpalomino** [comment]
+1

**Comment by akrabat** [comment]
PR #98 fixes the README so that you pass in a `Uri` object to the `TwigExtension` constructor.

Using a string for `$uri` should be considered deprecated.
