### ISSUE TITLE
How to specify subdirectories...

### ISSUE THREAD

**Issue by vjaykoogu** [slimphp/Twig-View#7]
How to specify subdirectories....

my directory structure.

A ->
       --> AA
       --> BB

```
Type: Twig_Error_Loader
Message: There are no registered paths for namespace "admin" in "menus/index.twig" at line 54.
File: /home/vijaykoogu/voicepace/vendor/twig/twig/lib/Twig/Loader/Filesystem.php
Line: 182
```

**Comment by akrabat** [comment]
I would expect this:

```php
$app->register(new \Slim\Views\Twig('path/to/templates', [
    'cache' => false,
    'debug' => true,
]));

$app->get('foo/bar', function ($request, $response, $args) {
    return $this['view']->render($response, 'foo/bar.twig');
});
```

To render the template: `path/to/templates/foo/bar.twig`.

alternatively, if you have multiple top level template directories, you can pass an array as the first parameter to `\Slim\Views\Twig` like this:

```php
$app->register(new \Slim\Views\Twig(['path/to/templates1', 'path/to/templates2'], [
        'cache' => false,
        'debug' => true,
]));
```

**Comment by bORm** [comment]
Hove use it?

**Comment by bORm** [comment]
Okey, i understand
But, what about the same files name?

**Comment by erdemece** [comment]
@bORm how do you use this in view->render  ?

**Comment by bORm** [comment]
@erdemece
`$this->view->render($res, '@admin/home.twig', []);`
