### ISSUE TITLE
Twig 2.x requires PHP 7 (readme update)

### ISSUE THREAD

**Issue by ccwebdesign** [slimphp/Twig-View#74]
Already known here: https://github.com/slimphp/Twig-View/pull/70, but just a quick note -- might be worth highlighting this requirement specifically in the readme (maybe under install, too), since it could be overlooked.

Running various versions of PHP locally as needed, so composer update changed to Twig 2.x. Production server was running PHP 5.6 (so it broke briefly).

**Comment by akrabat** [comment]
Good point. 

Of course, composer has:

    "config": {
        "platform": {
            "php": "5.6.19"
        }
    },

For this.

**Comment by ccwebdesign** [comment]
Good to know -- thanks!

**Comment by chrissound** [comment]
Can we highlight the latest version compatible with PHP 5.* ?

**Comment by silentworks** [comment]
@chrissound that would be the the current version. Just make sure you have Twig 1.* installed or follow the instructions by @akrabat above.

**Comment by geggleto** [comment]
Looks resolved.

**Comment by SJ-STEPHEN** [comment]
Problem 1
    - Installation request for twig/twig v2.4.3 -> satisfiable by twig/twig[v2.4.3].
    - twig/twig v2.4.3 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement.

  Problem 2
    - twig/twig v2.4.3 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - slim/twig-view 2.2.0 requires twig/twig ^1.18|^2.0 -> satisfiable by twig/twig[v2.4.3].
    - Installation request for slim/twig-view 2.2.0 -> satisfiable by slim/twig-view[2.2.0].
