### ISSUE TITLE
isCurrentPath() is not working with subdirectory

### ISSUE THREAD

**Issue by Nkoyan** [slimphp/Twig-View#75]
I modified it to work with my installation : 
```php
public function isCurrentPath($name)
{
    if ($this->uri->getBasePath()) {
        if ($this->uri->getPath() == '/') {
            return $this->router->pathFor($name) === $this->uri->getBasePath() . '/';
        } else {
            return $this->router->pathFor($name) === $this->uri->getBasePath() . '/' . $this->uri->getPath();
        }
    } else {
        return $this->router->pathFor($name) === $this->uri->getPath();
    }
}
```

**Comment by davidzoli** [comment]
Works great!
Please make a pull request or a fork. I have to make this after every composer install or update.
I hope it will be added soon.

**Comment by davidzoli** [comment]
Any ideas on variables in the url?
I mean if the url in the routes ex. is ```/users/edit/{id}``` the last return won't give true in the solution above.

**Comment by koelle25** [comment]
@sawa74 Perfect, I had the same problem, now it's working. Thanks!
@davidzoli [#80](https://github.com/slimphp/Twig-View/pull/80) should do the trick I think.
