### ISSUE TITLE
Docs lacking forcing Twig 2.0

### ISSUE THREAD

**Issue by AlexNodex** [slimphp/Twig-View#81]
Hi.

The docs are a little lacking when it comes to using twig 2.x

Can they be updated to reflect how to force usage of twig 2.x?

**Comment by tflight** [comment]
Twig 2.x requires PHP 7+, but this component doesn't. If you don't have a `platform` defined in the `composer.json` for your project, composer will install the version applicable to the PHP version composer is running under. Thus, if composer is running under PHP version 5, you will get Twig version 1.x. If composer is running under PHP 7+, you will get Twig version 2.x.

If you wish to force something different, for example if composer is run under PHP 5 and you want to build for PHP7+, then you can tell that to composer through your platform-config in `composer.json`.

```
    "config": {
        "platform": {
            "php": "7.0.18"
        }
    },
```

**Comment by AlexNodex** [comment]
Makes sense, thanks a lot

**Comment by akrabat** [comment]
Free free to PR an update to the README :)
