### ISSUE TITLE
a problem about twig

### ISSUE THREAD

**Issue by JokerBruceChan** [slimphp/Twig-View#85]
i am using twig in my project, i have a problem about the twig.
-----------------------------------------------------------------------
public function postSignUp(Request $request, Response $response)
{
        var_dump($request->getParams());
}
-----------------------------------------------------------------------
I think the result should be
------------------------------------
string(15) "test@domain.com"
  ["name"]=>
  string(4) "test"
  ["password"]=>
  string(12) "testpassword"
}
------------------------------------
but actually the browser show me  
-------------------------------------------------------------------------------------
string(15) "test@domain.com" ["name"]=> string(4) "test" ["password"]=> string(12) "testpassword" }
-------------------------------------------------------------------------------------

**Comment by danopz** [comment]
1. Looks exactly the same for me
2. Please reformat the text
3. Github issues are not for support questions, for this you can use [Stackoverflow](https://stackoverflow.com/questions/tagged/slim)

**Comment by JokerBruceChan** [comment]
@danopz thank you, i will ask the question on Stackoverflow.
