### ISSUE TITLE
Fatal error: Class 'Slim\Views' not found

### ISSUE THREAD

**Issue by Sirjoseph94** [slimphp/Twig-View#86]
I keep getting this error when i try to use the twig template engine with Slim. 
this is my composer.json 

{
    "require": {
        "slim/slim": "^3.8",
        "directus/sdk": "0.2.*",
        "slim/twig-view": "dev-master"

    },

    "minimum-stability": "dev",
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/wellingguzman/zend-db"
        }
    ]
}

below is a screen shot of the codes

![capture](https://user-images.githubusercontent.com/21038634/28661004-24ec522a-72ad-11e7-98d7-530ceff873e1.PNG)

**Comment by geggleto** [comment]
We cannot support your use of a private repo. Please use the public repo.
