### ISSUE TITLE
Response Immutability

### ISSUE THREAD

**Issue by ccwebdesign** [slimphp/Twig-View#87]
Just ran into an odd issue where a response was being preserved by reference, though I'm still not certain how.

Think I narrowed this down to the slim/twig-view rendering method:
```
/**
 * Output rendered template
 *
 * @param ResponseInterface $response
 * @param  string $template Template pathname relative to templates directory
 * @param  array $data Associative array of template variables
 * @return ResponseInterface
 */
public function render(ResponseInterface $response, $template, $data = [])
{
     $response->getBody()->write($this->fetch($template, $data));

     return $response;
}
```

Question: shouldn't this be preserving the immutability of the response? ie. $response = $response->...

Or is it something related to the Twig Environment?

Or is it the write method from Slim that's breaking things (by returning the response, rather than a clone / new one)?

Thanks for any insight you can provide. XD

**Comment by akrabat** [comment]
The body of a response is a stream and so is not immutable.

**Comment by ccwebdesign** [comment]
@akrabat 
Gotcha. Thanks!

Looking further into it, found:
http://www.php-fig.org/psr/psr-7/meta/#why-are-streams-mutable

Wouldn't it be clearer to generate a new response if the body changed? Or is there a good way to use / set the response to readonly streams?

Or is there something we can do with Slim / slim-twig to (attempt to) preserve response (message) immutability moving forward?

**Comment by akrabat** [comment]
You could write your own PSR-7 Response object that did it and then use it with Slim.

**Comment by ccwebdesign** [comment]
Got it -- thanks for the suggestion.
