### ISSUE TITLE
Problems with router/response and render method.

### ISSUE THREAD

**Issue by namaless** [slimphp/Twig-View#9]
From documentation:
```
// Define named route
$app->get('/hello/{name}', function ($request, $response, $args) {
    $this['view']->render('profile.html', [
        'name' => $args['name']
    ]);
})->setName('profile');
```
but i give error because i not pass the response object with first param to render method, so i edited with this:
```
// Define named route
$app->get('/hello/{name}', function ($request, $response, $args) {
    return $this['view']->render($response, 'profile.html', [
        'name' => $args['name']
    ]);
})->setName('profile');
```
Added the return because the router waiting the response object and in reference to this issue https://github.com/slimphp/Twig-View/issues/8 I edited with this:
```
public function render(ResponseInterface $response, $template, array $data = [])
    {
        $response->getBody()->write($this->fetch($template, $data));
        return $response;
    }
```
Anyone have the same error? Ofc I use the latest dev version of slim.

With this modifications all working correctly.

**Comment by akrabat** [comment]
The return issue is fixed now, via #5.
The documentation in the README has also been updated now.

Thanks for the report.
