### ISSUE TITLE
What is the purpose of defaultVariables (vs addGlobal)?

### ISSUE THREAD

**Issue by jordanlev** [slimphp/Twig-View#94]
Curious if I'm missing something with the undocumented "defaultVariables" feature, or if it's just an accident of history...

Is there any use-case where "defaultVariables" offers any benefit over using twig's built-in [Globals](https://twig.symfony.com/doc/2.x/advanced.html#globals) method?

For example:

    $this->view->getEnvironmnent()->addGlobal('myVar', 123);

...versus:

    $this->view['myVar'] = 123

Seems that a proxy method could be added to Twig-View (like the `addExtension` method) and this would serve the same purpose without having to clutter up the Slim\Views\Twig class with that ArrayAccess implementation. Or perhaps there's something that can be done (or is used elsewhere in the system) with the "defaultVariables" thing that can't be done with twig's built-in globals functionality?

Thanks!

**Comment by akrabat** [comment]
It's an accident of history!

**Comment by akrabat** [comment]
I suppose, really, the array access implementation should manipulate the Twig gobals.
